### ISSUE TITLE
tcp-streams-0.6.0.0 and tcp-streams-openssl-0.6.0.0 testsuite cert expired

### ISSUE THREAD

**Issue by juhp** [winterland1989/tcp-streams#5]
In the Stackage Nightly build:

```
> /tmp/stackage-build14/tcp-streams-0.6.0.0$ dist/build/testsuite/testsuite
TCP:
  network/socket: [OK]
TLS:
testsuite: HandshakeFailed (Error_Protocol ("certificate has expired",True,CertificateExpired))
  network/socket: [Failed]
ERROR: Network.Socket.sendBuf: resource vanished (Connection reset by peer)
  network/https: [OK]

         Test Cases  Total      
 Passed  2           2          
 Failed  1           1          
 Total   3           3          
```

```
> /tmp/stackage-build14/tcp-streams-openssl-0.6.0.0$ dist/build/testsuite/testsuite
TCP:
  network/socket: [Failed]
ERROR: Network.Socket.bind: resource busy (Address already in use)
OpenSSL:
testsuite: ProtocolError "error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed"
  network/socket: [Failed]
ERROR: ProtocolError "error:140E0197:SSL routines:SSL_shutdown:shutdown while in init"
  network/https: [OK]

         Test Cases  Total      
 Passed  1           1          
 Failed  2           2          
 Total   3           3          
```

**Comment by winterland1989** [comment]
Oh, my bad, i make that certificate for testing, and i has expired indeed, i'll update with a new one.

**Comment by juhp** [comment]
Sorry to push, but when do you think you can update it?

This is blocking Stackage LTS 8+ builds now too.

**edit**: well I can allow the testsuites to fail in LTS too, but I would prefer to avoid that, since it will also affect future builds, even after you fix the cert.

**Comment by winterland1989** [comment]
I have push a new commit and test should be fine now, to make stackage snapshot work i have to make a new release right? Let's wait the CI finish.

**Comment by juhp** [comment]
Yes please, thanks a lot!

**Comment by juhp** [comment]
Thank you - I see you made 1.0.1.0 releases - however Stackage is still on 0.6.0.0 due to fpco/stackage#2334. So maybe it is better we just allow the testsuite to fail for LTS for now, unless you want to make 0.6.1.0 releases?

For Nightly we will remove all upper bound constaints soon as we are moving to ghc-8.2.1.

**Comment by winterland1989** [comment]
Alright, please disable the test suit, thanks.

**Comment by bergmark** [comment]
passed on the ghc 8.2.2 nightly so I think this can be closed.

**Comment by winterland1989** [comment]
@bergmark Thanks for the info.
